/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-30 09:38:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<footer id=\"footer\" class=\"block block-bg-grey-dark\"\r\n");
      out.write("\tdata-block-bg-img=\"img/bg_footer-map.png\"\r\n");
      out.write("\tdata-stellar-background-ratio=\"0.4\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\" id=\"contact\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t<strong>CMC Laptop</strong> <br> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-map-pin fa-fw text-primary\"></i> CMC Tower, 11 Duy\r\n");
      out.write("\t\t\t\t\tTân, Dịch Vọng Hậu, Cầu Giấy, Hà Nội <br> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-phone fa-fw text-primary\"></i> 0243.333.333 <br>\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-envelope-o fa-fw text-primary\"></i> info@cmc.com.vn\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<h4 class=\"text-uppercase\">Liên hệ với chúng tôi:</h4>\r\n");
      out.write("\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sendmessage\">Gửi góp ý thành công!</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"errormessage\"></div>\r\n");
      out.write("\t\t\t\t\t<form action=\"\" method=\"post\" role=\"form\" class=\"contactForm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Name\" data-rule=\"minlen:4\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter at least 4 chars\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Email\" data-rule=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter a valid email\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"subject\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"subject\" placeholder=\"Subject\" data-rule=\"minlen:4\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter at least 8 chars of subject\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"message\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-rule=\"required\" data-msg=\"Please write something for us\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">Send Message</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4 class=\"text-uppercase\">Follow Us On:</h4>\r\n");
      out.write("\t\t\t\t<div class=\"social-media social-media-stacked\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook fa-fw\"></i> Facebook</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\"><i class=\"fa fa-google-plus fa-fw\"></i> Google+</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row subfooter\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<p>Bản quyền © CMC Laptop</p>\r\n");
      out.write("\t\t\t\t<div class=\"credits\">\r\n");
      out.write("\t\t\t\t\tPhát triển bởi <a href=\"https://fb.com/ngocdoan1711\">Ngọc Đoàn</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"#top\" class=\"scrolltop\">Top</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
