/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-30 16:27:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>CMC Laptop</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/icons/favicon.png\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/owlcarousel/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/owlcarousel/owl.theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/owlcarousel/owl.transitions.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"page-index has-hero\">\r\n");
      out.write("\t<div id=\"background-wrapper\" class=\"buildings\"\r\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.1\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"hero\" id=\"highlighted\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<div id=\"highlighted-slider\" class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-slider\" data-toggle=\"owlcarousel\"\r\n");
      out.write("\t\t\t\t\t\tdata-owlcarousel-settings='{\"singleItem\":true, \"navigation\":true, \"transitionStyle\":\"fadeUp\"}'>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-md-push-6 item-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"h1 text-weight-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tSản phẩm chính hãng tại <span class=\"text-primary\">Laptop\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tCMC</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-md-pull-6 hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/slides/slide1.png\" alt=\"Slide 1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"center-block img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6 text-right-md item-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"h1 text-weight-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"text-primary\">Laptop GAMING </span> cấu hình cực\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcao\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more btn-lg\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-plus\"></i> Xem ngay</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6 hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/slides/slide2.png\" alt=\"Slide 2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"center-block img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<div class=\"mission text-center block block-pd-sm block-bg-noise\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-shadow-white\">\r\n");
      out.write("\t\t\t\t\tLaptop CMC chuyên cung cấp các sản phẩm laptop xách tay chất lượng,\r\n");
      out.write("\t\t\t\t\tchính hãng nhập khẩu 100% từ Mỹ. <a href=\"#\" class=\"btn btn-more\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-plus\"></i>Xem thêm</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"showcase block block-border-bottom-grey\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h2 class=\"block-title\">Sản phẩm nổi bật</h2>\r\n");
      out.write("\t\t\t\t<p>Chúng tôi hiểu rằng con đường phát triển đúng đắn và vững\r\n");
      out.write("\t\t\t\t\tchắc nhất là mang đến cho khách hàng những sản phẩm chất lượng và\r\n");
      out.write("\t\t\t\t\tgiá cả hợp lý, bên cạnh đó là chế độ hậu mãi và dịch vụ chăm sóc\r\n");
      out.write("\t\t\t\t\tsau bán hàng luôn tốt nhất. Chúng tôi luôn đặt “uy tín” lên hàng\r\n");
      out.write("\t\t\t\t\tđầu nhất là đối với mặt hàng kinh doanh là laptop nhập khẩu.</p>\r\n");
      out.write("\t\t\t\t<div class=\"item-carousel\" data-toggle=\"owlcarousel\"\r\n");
      out.write("\t\t\t\t\tdata-owlcarousel-settings='{\"items\":4, \"pagination\":false, \"navigation\":true, \"itemsScaleUp\":true}'>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/AdvanceJava/detailproduct.jsp\" class=\"overlay-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/AdvanceJava/detailproduct.jsp\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/AdvanceJava/detailproduct.jsp\" class=\"btn btn-more\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-plus\"></i>Xem thêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product2.jpg\" alt=\"Product 2 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 2</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product3.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"showcase block block-border-bottom-grey\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h2 class=\"block-title\">Sản phẩm bán chạy</h2>\r\n");
      out.write("\t\t\t\t<p>Chúng tôi hiểu rằng con đường phát triển đúng đắn và vững\r\n");
      out.write("\t\t\t\t\tchắc nhất là mang đến cho khách hàng những sản phẩm chất lượng và\r\n");
      out.write("\t\t\t\t\tgiá cả hợp lý, bên cạnh đó là chế độ hậu mãi và dịch vụ chăm sóc\r\n");
      out.write("\t\t\t\t\tsau bán hàng luôn tốt nhất. Chúng tôi luôn đặt “uy tín” lên hàng\r\n");
      out.write("\t\t\t\t\tđầu nhất là đối với mặt hàng kinh doanh là laptop nhập khẩu.</p>\r\n");
      out.write("\t\t\t\t<div class=\"item-carousel\" data-toggle=\"owlcarousel\"\r\n");
      out.write("\t\t\t\t\tdata-owlcarousel-settings='{\"items\":4, \"pagination\":false, \"navigation\":true, \"itemsScaleUp\":true}'>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product2.jpg\" alt=\"Product 2 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 2</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product3.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"overlay-wrapper\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/showcase/product1.jpg\" alt=\"Product 1 image\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive underlay\"> <span class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"overlay-content\"> <span class=\"h4\">Product\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-details bg-noise\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"item-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Product 1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-more\"><i class=\"fa fa-plus\"></i>Xem\r\n");
      out.write("\t\t\t\t\t\t\t\tthêm</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"block-contained\">\r\n");
      out.write("\t\t\t<h2 class=\"block-title\"></h2>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default panel-pricing text-center\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/temp/BH.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"panel panel-default panel-pricing panel-pricing-highlighted text-center\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/temp/PIIN.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 text-center\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"panel panel-default panel-pricing panel-pricing-highlighted text-center\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/temp/ASSS.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script src=\"lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/stellar/stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
